version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3001:3001"
    restart: always
    env_file:
      - variables.txt
    depends_on:
      - api

  api:
    build:
      context: ./api
    ports:
      - "5001:5001"
    restart: always
    env_file:
      - variables.txt
    networks:
      mynet:
        ipv4_address: 172.20.0.12

networks:
  mynet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16